<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="keys.bin" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="keys.bin" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AssetsTools.NET" Version="3.0.5" />
    <PackageReference Include="CommandLineParser" Version="2.9.1" />
  </ItemGroup>

</Project>
